# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160325_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lens',
        ),
        migrations.AddField(
            model_name='user',
            name='cameras',
            field=models.ManyToManyField(to='users.Camera'),
        ),
        migrations.AddField(
            model_name='user',
            name='lenses',
            field=models.ManyToManyField(to='users.Lens'),
        ),
    ]
