# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160325_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'Lenses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
