# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160325_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'lenses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
    ]
