# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160325_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name': 'Lens', 'verbose_name_plural': 'lenses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='fav_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total number of favorites'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_count',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Total number of views'),
        ),
    ]
