# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160325_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cameras',
            field=models.ManyToManyField(blank=True, to='users.Camera'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenses',
            field=models.ManyToManyField(blank=True, to='users.Lens'),
        ),
    ]
