# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160326_0020'),
        ('photos', '0005_auto_20160416_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Camera'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Lens'),
        ),
    ]
